"""Initial migration

Revision ID: b29b2eca06c7
Revises:
Create Date: 2026-04-17 06:36:59.422461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b29b2eca06c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('category_id'),
        sa.UniqueConstraint('category_name')
    )
    op.create_table(
        'customer',
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('loyalty_points', sa.Integer(), nullable=False),
        sa.Column('is_registered', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('customer_id'),
        sa.UniqueConstraint('email')
    )
    op.create_table(
        'role',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('permissions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_name'), 'role', ['role_name'], unique=True)
    op.create_table(
        'tablezone',
        sa.Column('zone_id', sa.Integer(), nullable=False),
        sa.Column('zone_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('zone_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('floor_number', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('zone_id'),
        sa.UniqueConstraint('zone_name')
    )
    op.create_table(
        'product',
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('stock_quantity', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
        sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table(
        'systemuser',
        sa.Column('system_user_id', sa.Integer(), nullable=False),
        sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
        sa.PrimaryKeyConstraint('system_user_id')
    )
    op.create_index(op.f('ix_systemuser_email'), 'systemuser', ['email'], unique=True)
    op.create_table(
        'tablespot',
        sa.Column('table_id', sa.Integer(), nullable=False),
        sa.Column('zone_id', sa.Integer(), nullable=True),
        sa.Column('table_number', sa.Integer(), nullable=False),
        sa.Column('table_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('qr_code_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['zone_id'], ['tablezone.zone_id'], ),
        sa.PrimaryKeyConstraint('table_id'),
        sa.UniqueConstraint('table_code')
    )
    op.create_table(
        'workshop',
        sa.Column('workshop_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('max_capacity', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('instructor_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
        sa.PrimaryKeyConstraint('workshop_id')
    )
    op.create_table(
        'order',
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('system_user_id', sa.Integer(), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=True),
        sa.Column('order_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('subtotal', sa.Float(), nullable=False),
        sa.Column('tax_amount', sa.Float(), nullable=False),
        sa.Column('discount_amount', sa.Float(), nullable=False),
        sa.Column('total_amount', sa.Float(), nullable=False),
        sa.Column('order_date', sa.DateTime(), nullable=False),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
        sa.ForeignKeyConstraint(['system_user_id'], ['systemuser.system_user_id'], ),
        sa.ForeignKeyConstraint(['table_id'], ['tablespot.table_id'], ),
        sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table(
        'workshopschedule',
        sa.Column('schedule_id', sa.Integer(), nullable=False),
        sa.Column('workshop_id', sa.Integer(), nullable=False),
        sa.Column('schedule_date', sa.Date(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('available_slots', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshop_id'], ),
        sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table(
        'inventorymovement',
        sa.Column('movement_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('system_user_id', sa.Integer(), nullable=False),
        sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_cost', sa.Float(), nullable=True),
        sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('related_order_id', sa.Integer(), nullable=True),
        sa.Column('movement_date', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
        sa.ForeignKeyConstraint(['related_order_id'], ['order.order_id'], ),
        sa.ForeignKeyConstraint(['system_user_id'], ['systemuser.system_user_id'], ),
        sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_table(
        'notification',
        sa.Column('notification_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('related_order_id', sa.Integer(), nullable=True),
        sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
        sa.ForeignKeyConstraint(['related_order_id'], ['order.order_id'], ),
        sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table(
        'payment',
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('tip_amount', sa.Float(), nullable=False),
        sa.Column('payment_date', sa.DateTime(), nullable=False),
        sa.Column('system_user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
        sa.ForeignKeyConstraint(['system_user_id'], ['systemuser.system_user_id'], ),
        sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table(
        'workshopreservation',
        sa.Column('reservation_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('schedule_id', sa.Integer(), nullable=False),
        sa.Column('system_user_id', sa.Integer(), nullable=False),
        sa.Column('quantity_slots', sa.Integer(), nullable=False),
        sa.Column('total_price', sa.Float(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('reservation_date', sa.DateTime(), nullable=False),
        sa.Column('special_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
        sa.ForeignKeyConstraint(['schedule_id'], ['workshopschedule.schedule_id'], ),
        sa.ForeignKeyConstraint(['system_user_id'], ['systemuser.system_user_id'], ),
        sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table(
        'activitylog',
        sa.Column('log_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('related_order_id', sa.Integer(), nullable=True),
        sa.Column('related_payment_id', sa.Integer(), nullable=True),
        sa.Column('activity_date', sa.DateTime(), nullable=False),
        sa.Column('activity_metadata', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
        sa.ForeignKeyConstraint(['related_order_id'], ['order.order_id'], ),
        sa.ForeignKeyConstraint(['related_payment_id'], ['payment.payment_id'], ),
        sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table(
        'invoice',
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('payment_id', sa.Integer(), nullable=True),
        sa.Column('invoice_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=False),
        sa.Column('invoice_date', sa.DateTime(), nullable=False),
        sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
        sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
        sa.PrimaryKeyConstraint('invoice_id'),
        sa.UniqueConstraint('invoice_number'),
        sa.UniqueConstraint('order_id')
    )
    op.create_table(
        'orderitem',
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('reservation_id', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('subtotal', sa.Float(), nullable=False),
        sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('special_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
        sa.ForeignKeyConstraint(['reservation_id'], ['workshopreservation.reservation_id'], ),
        sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.drop_table('invoice')
    op.drop_table('activitylog')
    op.drop_table('workshopreservation')
    op.drop_table('payment')
    op.drop_table('notification')
    op.drop_table('inventorymovement')
    op.drop_table('workshopschedule')
    op.drop_table('order')
    op.drop_table('workshop')
    op.drop_table('tablespot')
    op.drop_index(op.f('ix_systemuser_email'), table_name='systemuser')
    op.drop_table('systemuser')
    op.drop_table('product')
    op.drop_table('tablezone')
    op.drop_index(op.f('ix_role_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_table('customer')
    op.drop_table('category')
    # ### end Alembic commands ###
